### ISSUE TITLE
Windows/MSVC support

### ISSUE THREAD

**Issue by gvanem** [AD-Vega/rtl-power-fftw#19]
I managed to compile and link `rtl_power_fftw` using MSVC-2017. Except for the `sigaction()` code in `interrupts.cxx`. With this simple patch, all seems to work:
```diff
--- a/src/interrupts.cxx 2017-07-06 12:04:27
+++ b/src/interrupts.cxx 2017-12-11 12:02:57
@@ -31,11 +31,15 @@
 }

 void set_CtrlC_handler(bool install) {
+#ifdef _WIN32
+  signal(SIGINT, CtrlC_handler);
+#else
   struct sigaction action;
   action.sa_handler = (install ? &CtrlC_handler : SIG_DFL);
   sigemptyset(&action.sa_mask);
   action.sa_flags = 0;
   sigaction(SIGINT, &action, nullptr);
+#endif
 }
```

Care to change that?

**Comment by alajovic** [comment]
Hi,

apologies for the late response, but this particular patch triggered a minor phylosophical crisis amongst the principal authors of rtl_power_fftw, and it had to stand for a while until we decided to include it. The problem is that none of the principal authors uses Windows, and so we are unable (and not even willing) to offer any support for it. Until now, we have thus carefully avoided giving an impression that Windows is supported in any way. The proposed change makes a hint in this direction, so we had to decide whether we want to break the unwritten rule or not.

On the other hand, rtl_power_fftw is our contribution to the community, and we strive to offer a program that everyone can benefit from and rely on. Extending the OS support makes the program available to a larger user base, so that's a move in the positive direction.

Ultimately, we decided that if only such a trivial modification is needed to make the program available to Windows users, we are willing to relax our position a bit and include it. We hope that the rest of the code is sufficiently platform-independent so that additional modifications will not be needed.

Patch applied and the new commit pushed. Thanks!
