### ISSUE TITLE
Integration time versus FFT bin size

### ISSUE THREAD

**Issue by mdasari823** [AD-Vega/rtl-power-fftw#21]
Hi,
What is integration time (-t or --time) parameter? I am unable to differentiate FFT bin size and this.

**Comment by alajovic** [comment]
Hi,

the _integration time_ essentially determines how much data the program will read from the device. If the receiver's sample rate is, say, 2 MHz, and the integration time is set to 1 second, the total amount of samples read from the device will be 2e6. If the integration time is set to 2 seconds, the total amount of samples will be 4e6 etc. Usually, the execution time of rtl_power_fftw is roughly equal to the integration time (but there are exceptions: see the man page for details).

I am not sure what parameter you are referring to as the "FFT bin size". rtl_power_fftw accepts the `--bins` parameter that sets the number of FFT bins – that is, the number of data points in a single spectrum.

**Comment by bershgal** [comment]
Hi, 
I also had a few questions about the operation of the rtl_power_fftw library:

If my integration time is set to 1 second and my sampling rate is 2 MHz, then the FFT will run after collecting 2e6 samples every time. Now let's assume the following scenarios:
            a. I set my number of bins to be 3e6 (i.e. my number of bins are greater than my window size of 
                2e6). How will the bins fill up. I am assuming that some of the bins will be empty.
            b. I set my number of bins to be 512 (i.e. my number of bins are less than my window size of 2e6). 
                How will the bins fill up in this case? 
Lastly, am I right in saying that the ideal case would be if both my number of bins and my window size are the same and both are a power of 2? 
From my understanding of FFT, it takes a signal of n samples in time and divides it into n signals each of 1 sample and each sample corresponds to a bin. 

Thanks

**Comment by KlemenBlokar** [comment]
Well, it's all in the code :-)

But on a more serious note, integration time parameter has nothing to do with FFT at all. Sometimes, in order to get your signal out of the noise, you need to average some individual spectra, as this improves your S/N ratio.

So, if we take, for example, spectra of 512 bins (to keep up to your desire of 2^N), we need to capture 512 samples and then perform FFT on them (the "bin size" is related to both the number of bins and the chosen samplerate, but that is beyond the scope of your question). If you want to average 10 spectra, you need to repeat this process 10 times. Altogether you will thus gather 5120 samples. Given the chosen samplerate, you can calculate how long the measurement will last. Sometimes, you are time-constrained, and want to average as many spectra as you can in the given time, whatever the number might be. In this case, you specify the time over which the spectra are captured and averaged, and rtl-power-fftw figures everything else for you. This is also the reason why you cannot set the number of averaged spectra and integration time together - you would overdetermine the system.

Hope it helps.

**Comment by KlemenBlokar** [comment]
Shall we close the issue now?

**Comment by mdasari823** [comment]
Yes sir. Thank you!
