### ISSUE TITLE
The baseline function is not working properly ...

### ISSUE THREAD

**Issue by ulrichloose** [AD-Vega/rtl-power-fftw#25]
if you want to scan a wide frequency range, only the number of bins specified in -b is accepted, even if the baseline file contains the total number of bins required.

In acquisition.cxx the size of the baseline file is compared only with params.N ...

// Check for suitability.
if ((int) baseline_values.size () == params.N) {

If you comment this out, the entire baseline file will be read, but only the first params.N bytes will be read with each pass.

for (int i = 0; i <params.N; i ++) {

Unfortunately I am an absolute layman in Python - maybe there will be a professional who will take care of the problem (;-)

**Comment by alajovic** [comment]
The baseline correction option is there to allow correcting for the receiver's baseband/IF characteristic. Let me explain. If you measure an RF source with a completely flat frequency characteristic (white noise), you expect to get a flat spectrum. However, as you may have noticed, the result with the RTL-SDR receivers isn't actually flat. It is shaped kind-of like a soft hat: the middle is a bit higher, then there is a shallow dip on both sides, after that the signal rises again before ultimately falling quite sharply off at the very edges. If you measure a white noise source at _any_ frequency, you will always get this same shape. In other words, the shape does not depend on the _absolute_ frequency, but rather on the _relative_ frequency within a spectrum from a single run. That's the receiver's IF/baseband characteristic. And since it's always there, it means that whatever source you measure, this shape will be imprinted on top of it. Baseline correction allows you to correct for this.

As you can see, baseline correction in `rtl_power_fftw` is applied to one span of the receiver's bandwidth at a time, therefore the number of the baseline points has to match the number of bins in one measurement (that's the `params.N` value). So the code is correct in that respect.

What you are trying to do is to compensate for a baseline over a wider frequency span. For this, you will have to do a post-processing step on your own. `rtl_power_fftw` is a data acquisition tool, and in following the Unix philosophy, it does _one_ thing, and does it well (hopefully, at least!). We try to keep it at that. Data processing, such as wide range baseline correction, thus falls outside of its scope. For your particular use-case, an external python script would be a perfect solution.

**Comment by ulrichloose** [comment]
Thank you for the explanation - my idea as a beginner was that the display could be linearized with this baseline file. Redirect a multi hop scan to a file without an input signal and then read this file as a baseline file. In the case of a scan with an input signal, the baseline file would then be deducted.

As an experiment, I commented out the size query of the baseline file in acquisition.cxx and expanded the read-in routine by the number of hops. Unfortunately that was a beginner's mistake? (:-)


static int runde = 0;
  //
  for (int i = 0; i < params.N; i++)
  {
    freq = tuned_freq + (i - params.N/2.0) * actual_samplerate / params.N;
    if( params.linear )
    {
      pwrdb = (data.pwr[i] / data.repeats_done / params.N / actual_samplerate)
                     - (params.baseline ? aux.baseline_values[i+(runde*params.N)] : 0);
    }
    else
    {
      pwrdb = 10*log10(data.pwr[i] / data.repeats_done / params.N / actual_samplerate)
                     - (params.baseline ? aux.baseline_values[i+(runde*params.N)] : 0);
    }

runde ++;

double min_overhang = actual_samplerate*params.min_overlap/100;
int hops = ceil((double(params.stopfreq - params.startfreq) - min_overhang) / (double(actual_samplerate) - min_overhang));

if (runde == hops) runde = 0;

**Comment by alajovic** [comment]
While you are of course free to hack on the `rtl_power_fftw` source to achieve the desired behavior, I think you will be much better off by writing a post-processor in whatever language you feel most comfortable with. As a plus, you can share the post-processor with anyone without them having to patch their existing `rtl_power_fftw`.

**Comment by ulrichloose** [comment]
I really don't want to spoil the beautiful tool, that's why I asked if the small bug could be fixed ...

From my point of view, it is incomprehensible why rtl_power_fftw on the one hand offers hopping over a wide frequency range, can read in its own data again, offers a baseline function, but at the same time limits reading to a single hop.

I am still of the opinion that this is not an explainable feature, it is a small bug.

My programming skills are very modest and the commenting out of the checking of the file length is due to this fact. The actual "patch" works fine - which is just another outer counter loop.

But that doesn't matter - my slightly modified version is enough for my purposes ...

**Comment by KlemenBlokar** [comment]
The problem with what you are trying to achieve is that what the baseline function is meant to do is to correct for the uneven response of the detector in a single acquisition - a scan is consisting of multiple acquisitions and the needed correction differs a lot for each setting of how the spectra overlap in the scan. Therefore, by allowing such a baseline we would disable the primary purpose of the baseline function and override it with something completely different. And I would not argue that what you want to achieve is not useful, it is just different than what baseline correction is. This is why @alajovic proposed to use another method to achieve your goal.

**Comment by ulrichloose** [comment]
Of course, I'm not an expert on the matter ...

I don't use the SDR stick for radio reception, but as a kind of "spectrum analyzer" for poor people. There are some tools such as QSpectrumanalyzer, which contains its own baseline function. Unfortunately, it only works with imported data from Soapy-Power. In principle, the frequency range, crop, etc. is transferred to soapy_power and this scan is saved once in a file without a measurement object. Then the measurement object is connected and the previously created data is simply subtracted mathematically. The result is then a zero line related to 0 db with little visible interference.

This is exactly what happens with rtl_power_fttw if you allow the baseline function over several hops. The result is even better than with soapy_power.

This may of course look completely different for other operating modes and this QSpectrum tool is certainly not particularly professional and does not take into account many things that are necessary for other applications ...

Just as a layperson, the motivation was not clear to me to only allow the baseline function via one hop if there is also hop support.

But now it is a lot clearer to me, thanks for the explanations!

**Comment by KlemenBlokar** [comment]
Maybe to clarify even more - and reiterate what @alajovic wrote -  the baseline correction is meant to primarily correct for differences in sensitivity of the detector for frequency offsets that are relative to the frequency that the tuner is tuned to - so in the most part you can **record baseline at one frequency and reuse it at another** (results are of course more flat if both frequencies are close together). But the correction you wish for, is also heavily dependent on frequency of the signal itself. So to correctly perform it, the **exact same settings** must be used for baseline and actual recordings. This makes it a more niche use-case and since it really is a simple subtraction, a dedicated tool should be simple to make and use.

If anyone comes around with such tools that use minimal additional depencencies (maybe python scripts that only use the python standard libraries?), I am not opposed to think about how we could include them in some "scripts" folder or something... to make it more discoverable for everyone.

And lastly, your patch of course does exactly what you need it to do - we are only hesitant to mix up the meaning of what baseline correction is for all the users.
