### ISSUE TITLE
Missing crop option

### ISSUE THREAD

**Issue by xmikos** [AD-Vega/rtl-power-fftw#3]
Original `rtl_power` has _crop_ option, which is extremely useful when doing long sweeps over multiple frequency hops (because edges of each hop are attenuated). Crop of at least 20% is needed for resulting spectrum plot to be smooth.

Can you please add this function too?

**Comment by KlemenBlokar** [comment]
I will consider this option. But for the smoothness of the spectrum rtl_power_fftw provides a neat solution - you can subtract the baseline of the receiver from every individual spectrum. This way, the composite spectrum is smooth even with the elonics e4000 tuner that has the central bulge.

All you need to do is to measure one "quiet" spectrum with the same number of bins and use the resultant file as a baseline.

**Comment by xmikos** [comment]
Subtracting baseline is great for some applications, but for my primary usecase crop is much more convenient option (I am developer of [QSpectrumAnalyzer](https://github.com/xmikos/qspectrumanalyzer) - GUI for rtl_power - and would love to switch to rtl_power_fftw as a better backend).

**Comment by KlemenBlokar** [comment]
I am not very enthusiastic about including the crop option directly into rtl_power_fftw, because one of the things we particularly disliked in rtl_power is the fact that it obfuscates the output of FFT routine too much when outputting data - that is why we decided to always output whole spectrum, regardless of overlap; one can always post process things for each individual use-case.  

However, we wish to make the program useful for _any_ use-case, and we are keen to help you in your case. I was contemplating your idea with @alajovic and we came to a conclusion that we could in the future include a post-processor with rtl_power_fftw to cover such data manipulations.

And if I understand you correctly, you could post-process the data easily if we included the option for the user to decide the minimum amount of spectral overlap permissible when hopping. This seems like a generally useful option and I am willing to implement it right away. :-)

**Comment by xmikos** [comment]
Yes, if you allow to choose minimum amount of overlap, it would be enough for me, I can crop it myself ;-) Thank you very much for being so helpful!

**Comment by KlemenBlokar** [comment]
I would be very happy if you would find `rtl_power_fftw` useful, so I am glad to help as much as I can.

I implemented the `--overlap` option, you can now specify the minimum amount of overlap in percentage of the width of single spectrum. Tell me if it works for you this way. If it works ok, I can close the issue. ;-) :-)

And if you have any further wish/question, feel free to ask.

**Comment by xmikos** [comment]
@KlemenBlokar I have tried it and it seems `--overlap` is always 50% when setting `-o 1` to `-o 50` (it doesn't change at all). Only `-o 0` and `-o 51` to `-o 100` works as expected.

**Comment by xmikos** [comment]
Well, minimum overlap of 50% has been caused by distribution of frequency hops when testing (range has been `-f 88M:92M -r 2000000`). If I use bigger range with more hops, it works as expected. So ignore this, sorry for confusion...

**Comment by KlemenBlokar** [comment]
No problem, I was confused myself when testing it - the final overlap can be quite bigger than minimum requested for small ranges. :-)

So with this, I can close this issue for now.
